server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
          - Path=/first/**
          filters:
#            - AddRequestHeader=first-request, first-requests-header
#            - AddResponseHeader=first-request, first-response-header
            - CustomFilter
        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second/**
          filters:
#            - AddRequestHeader=second-request, second-requests-header
#            - AddResponseHeader=second-request, second-response-header
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there. I'm Second Service
                preLogger: true
                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true